# Lancement de pgadmin 
- name : "Launch pgAdmin container"
  docker_container:
    name: "{{ pgadmin_container }}"
    image: "{{ pgadmin_image }}"
    ports:
      - "{{ pgadmin_port }}:80"
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_password }}"
 
    volumes:
      - "{{ pgadmin_data }}:/var/lib/pgadmin"
      - "{{ pgadmin_config }}:/pgadmin4/servers.json"
      - "{{ pgadmin_pass }}:/pgpass"
